### ISSUE TITLE
正文中出现双引号"导致无法替换的问题

### ISSUE THREAD

**Issue by ghost** [OrangeX4/OrangeX4-HyperSnips#34]
配置文件中使用
```
snippet aaa "aaa" A
\\\"bbbb
endsnippet
```
此时输入`aaa`无法被替换成`\"bbbb`，而且是根本不触发替换。
同理，
```
snippet aaa "aaa" A
\"bbbb
endsnippet
```
也无法触发替换，只有不出现`"`时才能正常替换。

**Comment by ghost** [comment]
![图片](https://github.com/OrangeX4/OrangeX4-HyperSnips/assets/94974341/dfb54e0a-6750-4b77-a799-cb7c871089bd)
又仔细看了眼，出现"的时候会导致整个hsnips文件都无法替换。报错详细信息如下
```
[error] SyntaxError: missing ) after argument list
	at new Function (<anonymous>)
	at Object.parse (c:\Users\myname\.vscode\extensions\orangex4.hsnips-0.4.8\out\parser.js:115:22)
	at c:\Users\myname\.vscode\extensions\orangex4.hsnips-0.4.8\out\extension.js:37:57
	at Generator.next (<anonymous>)
	at c:\Users\myname\.vscode\extensions\orangex4.hsnips-0.4.8\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\myname\.vscode\extensions\orangex4.hsnips-0.4.8\out\extension.js:4:12)
	at loadSnippets (c:\Users\myname\.vscode\extensions\orangex4.hsnips-0.4.8\out\extension.js:25:12)
	at c:\Users\myname\.vscode\extensions\orangex4.hsnips-0.4.8\out\extension.js:110:13
	at g.value (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:19731)
	at r.y (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at r.z (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1972)
	at r.fire (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2188)
	at D.$acceptModelSaved (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:70289)
	at d.S (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5520)
	at d.Q (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5286)
	at d.M (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:4376)
	at d.L (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:3455)
	at g.value (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:2242)
	at r.y (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at r.fire (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at n.fire (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14073)
	at g.value (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:8051)
	at r.y (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at r.fire (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at n.fire (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14073)
	at MessagePortMain.<anonymous> (c:\Users\myname\AppData\Local\Programs\Microsoft_VS_Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:6331)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285)
```
